// verify: debug ok
// verify: debug miri-ok
//! ch04-05's WithBudget again, with the pin projection generated by `pin_project_lite` instead of
//! written by hand. `#[pin]` marks the structurally pinned field; `project()` hands back
//! `Pin<&mut F>` for it and `&mut u32` for the rest. No `unsafe` in this file.
use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll};

struct YieldOnce(bool);
impl Future for YieldOnce {
    type Output = ();
    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<()> {
        if self.0 {
            return Poll::Ready(());
        }
        self.0 = true;
        cx.waker().wake_by_ref();
        Poll::Pending
    }
}

async fn checksum() -> usize {
    let data = [1u8, 2, 3, 4];
    let view: &[u8] = &data;
    YieldOnce(false).await;
    view.iter().map(|&b| b as usize).sum()
}

#[derive(Debug)]
struct BudgetExceeded;

pin_project_lite::pin_project! {
    struct WithBudget<F> {
        #[pin]
        inner: F,
        polls_left: u32,
    }
}

impl<F: Future> Future for WithBudget<F> {
    type Output = Result<F::Output, BudgetExceeded>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let this = self.project(); // this.inner: Pin<&mut F>, this.polls_left: &mut u32
        if *this.polls_left == 0 {
            return Poll::Ready(Err(BudgetExceeded));
        }
        *this.polls_left -= 1;
        this.inner.poll(cx).map(Ok)
    }
}

fn is_unpin<T: Unpin>() -> bool {
    true
}

fn main() {
    let ok = futures::executor::block_on(WithBudget { inner: checksum(), polls_left: 5 });
    let too_slow = futures::executor::block_on(WithBudget { inner: checksum(), polls_left: 1 });
    println!("budget 5: {ok:?}");
    println!("budget 1: {too_slow:?}");
    // The generated Unpin impl is conditional: WithBudget<F> is Unpin exactly when F is.
    println!("WithBudget<YieldOnce> is Unpin: {}", is_unpin::<WithBudget<YieldOnce>>());
}
